AWS-16

diff --git a/.github/workflows/Terraform-Plan.yml b/.github/workflows/Terraform-Plan.yml
--- a/.github/workflows/Terraform-Plan.yml
+++ b/.github/workflows/Terraform-Plan.yml
@@ -40,9 +40,9 @@ jobs:
       id: plan
       if: github.event_name == 'push'
       run: terraform plan -no-color
-      continue-on-error: true
+      #continue-on-error: true
 
-    - name: Terraform Plan Status 
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+   # - name: Terraform Plan Status 
+   #   if: steps.plan.outcome == 'failure'
+   #   run: exit 1
       
